### ISSUE TITLE
иконки заменить

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/tamir#34]
![icon1](https://cloud.githubusercontent.com/assets/8439283/9563627/261483ca-4e92-11e5-9f83-794340b18564.png)
![icon2](https://cloud.githubusercontent.com/assets/8439283/9563628/261524d8-4e92-11e5-9b19-ef0f6aec2052.png)
![icon3](https://cloud.githubusercontent.com/assets/8439283/9563626/2613da2e-4e92-11e5-994f-0698f693609a.png)
![icon4](https://cloud.githubusercontent.com/assets/8439283/9563629/26174ff6-4e92-11e5-98f8-d342542d3ebe.png)

и убрать рамку вокруг них

**Comment by olleskiv** [comment]
заменить на что?

**Comment by dadakax** [comment]
они там есть, просто они белого цвета лол))
