### ISSUE TITLE
изменить шрифт заголовков на тетру 

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/tamir#35]
https://vk.com/wall-50911295?q=tetra&w=wall-50911295_824%2Fall

**Comment by dadakax** [comment]
Оль, основной шрифт тоже подбери, пожалуйста) а то того, что сейчас букві разной вісоті)

**Comment by dadakax** [comment]
этот шрифт, считаю не очень 
![image](https://cloud.githubusercontent.com/assets/8439283/9563856/871b092e-4e9b-11e5-80eb-4e4bde68f01a.png)

**Comment by dumbik** [comment]
закрываю задачу пока нет никаких аргументов
